require 'mimic'
require 'attribute'
require 'reflect'

require 'subst_attr/substitute/null_object'
require 'subst_attr/substitute'
require 'subst_attr/attribute'
require 'subst_attr/macro'
require 'subst_attr/activate'
require 'subst_attr/subst_attr'
